
GET http://localhost:3001/api/employee HTTP/1.1
Content-Type: application/json

{
}

######
POST http://localhost:3001/api/service HTTP/1.1
Content-Type: application/json

{
    "type":"affittp",
    "description":"rilascio della pensione"
}


#####
POST http://localhost:3001/api/ticket HTTP/1.1
Content-Type: application/json

{
    "service":3,
    "officer":1,
    "help_desk_number":3
}
